feat(pre-commit): Pre commit parametrisation
PaloAltoNetworks/terraform-modules-vmseries-ci-workflows pull request #14
Opened 2023-01-30 19:28 UTC by horiagunica

## Description

- Parametrised pre-commit workflow to run tests based on workflow inputs from source repository
  - New input defined is : pre-commit-hooks
  - Mandatory : Yes
  - Default value (includes all checks) : terraform_fmt terraform_docs terraform_tflint checkov
- Removed checkov workflow entirely (now runs based on pre-commit input while lusing local .pre-commit.yml in local source repository)

## Motivation and Context

- Centralised CI workflows enhancement and pre-commit parametrisation .

## How Has This Been Tested?

- Used a separate repo that called sourced workflows CI in current "pre-commit-parametrisation" development branch.
  - Tested checkov fail/pass
  - Tested terraform fmt fail/pass
  - Tested terraform docs fail/pass

## Screenshots (if appropriate)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

2023-02-16 07:51 UTC, FoSix requested changes

2023-02-16 07:51 UTC, FoSix commented on .github/workflows/actions_release_ci.yml
> +      - name: get diff with base branch
as discussed, this can even be the same CI, just doing different things depending on the trigger

2023-02-16 08:18 UTC, FoSix commented
and one more bug, you did not change the release CI :) it still refers to the original `_checkov.yml` workflow :) 

see [here](https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/blob/a76477bc5c8415d8553334527d780472ab704a14/.github/workflows/release_ci.yml#L71)

```
[Invalid workflow file: .github/workflows/release_ci.yml#L21](https://github.com/PaloAltoNetworks/vm-series-gh-actions/actions/runs/4191953420/workflow)
error parsing called workflow
".github/workflows/release_ci.yml"
-> "PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/release_ci.yml@pre-commit-parametrization" (source branch with sha:8db5c40195168451ca1624351a08f8ca025b4b9e)
--> "./.github/workflows/_checkov.yml"
: failed to fetch workflow: workflow was not found.
```

2023-02-16 15:38 UTC, horiagunica commented on README.md
> +        p_prereq-->p_pre_commit(Run validation strategy: matrix)
Modified to " p_prereq-->p_pre_commit(Execute pre-commit hooks based on input parametrization) "

2023-02-20 11:30 UTC, FoSix approved these changes
👍🏻

2023-02-20 11:31 UTC, merged